version: '3'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    depends_on:
      - database

  dash:
    build: ./dash
    ports:
      - "8050:8050"
    depends_on:
      - database

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
